-- Align the live MySQL schema with the Prisma models used by the deployed API.
-- Earlier migrations created PascalCase/camelCase tables, while the Prisma schema
-- later drifted toward snake_case mappings. These additive checks keep existing
-- production data intact and make auth/catalog queries safe to run.

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `User` ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'User'
  AND COLUMN_NAME = 'updatedAt';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

CREATE TABLE IF NOT EXISTS `Profile` (
  `id` VARCHAR(191) NOT NULL,
  `email` VARCHAR(191) NOT NULL,
  `firstName` VARCHAR(191) NULL,
  `lastName` VARCHAR(191) NULL,
  `avatarUrl` VARCHAR(191) NULL,
  `country` VARCHAR(191) NULL,
  `phone` VARCHAR(191) NULL,
  `theme` VARCHAR(191) NOT NULL DEFAULT 'system',
  `locale` VARCHAR(191) NOT NULL DEFAULT 'en',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Course` ADD COLUMN `educatorId` VARCHAR(191) NULL',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Course'
  AND COLUMN_NAME = 'educatorId';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Course` ADD COLUMN `authorName` VARCHAR(191) NULL',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Course'
  AND COLUMN_NAME = 'authorName';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Course` ADD COLUMN `authorAvatarUrl` VARCHAR(191) NULL',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Course'
  AND COLUMN_NAME = 'authorAvatarUrl';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Course` ADD COLUMN `featured` BOOLEAN NOT NULL DEFAULT false',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Course'
  AND COLUMN_NAME = 'featured';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Course` ADD COLUMN `courseLevel` VARCHAR(191) NULL DEFAULT ''beginner''',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Course'
  AND COLUMN_NAME = 'courseLevel';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Course` ADD COLUMN `language` VARCHAR(191) NULL DEFAULT ''English''',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Course'
  AND COLUMN_NAME = 'language';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Course` ADD COLUMN `delivery` VARCHAR(191) NULL DEFAULT ''online''',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Course'
  AND COLUMN_NAME = 'delivery';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Course` ADD COLUMN `durationHours` INTEGER NULL DEFAULT 0',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Course'
  AND COLUMN_NAME = 'durationHours';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Course` ADD COLUMN `passMark` INTEGER NULL DEFAULT 70',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Course'
  AND COLUMN_NAME = 'passMark';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Course` ADD COLUMN `sequentialModules` BOOLEAN NOT NULL DEFAULT true',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Course'
  AND COLUMN_NAME = 'sequentialModules';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Course` ADD COLUMN `requireAssessment` BOOLEAN NOT NULL DEFAULT true',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Course'
  AND COLUMN_NAME = 'requireAssessment';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Course` ADD COLUMN `rejectionReason` VARCHAR(191) NULL',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Course'
  AND COLUMN_NAME = 'rejectionReason';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Course` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Course'
  AND COLUMN_NAME = 'createdAt';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Course` ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Course'
  AND COLUMN_NAME = 'updatedAt';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Course` ADD COLUMN `enrollmentCount` INTEGER NOT NULL DEFAULT 0',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Course'
  AND COLUMN_NAME = 'enrollmentCount';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Course` ADD COLUMN `level` VARCHAR(191) NULL DEFAULT ''beginner''',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Course'
  AND COLUMN_NAME = 'level';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Course` ADD COLUMN `publishedAt` DATETIME(3) NULL',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Course'
  AND COLUMN_NAME = 'publishedAt';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Course` ADD COLUMN `rating` DOUBLE NULL',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Course'
  AND COLUMN_NAME = 'rating';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Module` ADD COLUMN `videoUrl` VARCHAR(191) NULL',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Module'
  AND COLUMN_NAME = 'videoUrl';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Module` ADD COLUMN `fileUrl` VARCHAR(191) NULL',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Module'
  AND COLUMN_NAME = 'fileUrl';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Module` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Module'
  AND COLUMN_NAME = 'createdAt';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Module` ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Module'
  AND COLUMN_NAME = 'updatedAt';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Enrollment` ADD COLUMN `status` VARCHAR(191) NOT NULL DEFAULT ''active''',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Enrollment'
  AND COLUMN_NAME = 'status';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Enrollment` ADD COLUMN `paymentId` VARCHAR(191) NULL',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Enrollment'
  AND COLUMN_NAME = 'paymentId';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Enrollment` ADD COLUMN `rejectionReason` VARCHAR(191) NULL',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Enrollment'
  AND COLUMN_NAME = 'rejectionReason';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Enrollment` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Enrollment'
  AND COLUMN_NAME = 'createdAt';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT IF(
  COUNT(*) = 0,
  'ALTER TABLE `Enrollment` ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)',
  'SELECT 1'
) INTO @sql
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Enrollment'
  AND COLUMN_NAME = 'updatedAt';
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

CREATE TABLE IF NOT EXISTS `payments` (
  `id` VARCHAR(191) NOT NULL,
  `user_id` VARCHAR(191) NOT NULL,
  `course_id` VARCHAR(191) NOT NULL,
  `enrollment_id` VARCHAR(191) NULL,
  `reference` VARCHAR(191) NOT NULL,
  `method` VARCHAR(191) NOT NULL DEFAULT 'bank_transfer',
  `status` VARCHAR(191) NOT NULL DEFAULT 'pending',
  `amount_kobo` INTEGER NOT NULL DEFAULT 0,
  `proof_path` VARCHAR(191) NULL,
  `payer_name` VARCHAR(191) NULL,
  `note` TEXT NULL,
  `rejection_reason` VARCHAR(191) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `payments_reference_key` (`reference`),
  INDEX `payments_user_id_status_idx` (`user_id`, `status`),
  INDEX `payments_course_id_status_idx` (`course_id`, `status`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
